# Generated by Django 4.2.9 on 2026-03-02 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
